server:
  address: ":4000"

  # Path to the folder with the certificates file (cert.pem and key.pem) for using TLS
  certificate: "/etc/letsencrypt/live/"

  # Enables the development server with hot reload function (spans a vite server)
  developmentServer: false
  # Port on which the development server should listen to
  developmentServerPort: 5173

logging:
  # Minimum log Level for printing to the console (debug, info, warning, error, fatal)
  printLogLevel: info
  # Minimum log level for writing into the log file (debug, info, warning, error, fatal)
  writeLogLevel: warning

  # File path to log (empty = disabled)
  logFilePath: "/home/myUser/logs/ncDocConverter.live"